server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    location /static {
        alias /usr/share/nginx/html/static;
    }

    error_page 404 /index.html;
}
#
# listen 80;: Lắng nghe trên cổng 80 (HTTP).
# root /usr/share/nginx/html;: Đặt thư mục gốc là nơi chứa các file tĩnh của ứng dụng.
# index index.html;: File mặc định là index.html.
# location / { try_files $uri /index.html; }: Chuyển hướng tất cả các yêu cầu không tìm thấy file sang index.html (hỗ trợ ứng dụng React Router).
# location /static { alias /usr/share/nginx/html/static; }: Phục vụ các file tĩnh từ thư mục /static.
# error_page 404 /index.html;: Chuyển hướng lỗi 404 đến "index"
